import { Link } from "wouter";
import { ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-4xl mx-auto px-4 py-12">
        <Link href="/">
          <Button variant="ghost" className="mb-8" data-testid="button-back">
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back to Home
          </Button>
        </Link>

        <div className="prose prose-slate dark:prose-invert max-w-none">
          <h1 className="text-4xl font-bold mb-2">Terms of Service</h1>
          <p className="text-muted-foreground mb-8">Last updated: November 7, 2025</p>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">1. Acceptance of Terms</h2>
            <p>
              By accessing and using Tivideo, you accept and agree to be bound by these Terms of Service. 
              If you do not agree to these terms, please do not use our service.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">2. Description of Service</h2>
            <p className="mb-4">
              Tivideo is an AI-powered video script generation application that provides:
            </p>
            <ul className="list-disc pl-6 mb-4">
              <li>AI-generated video scripts based on user input</li>
              <li>Text-to-speech conversion with mood-based voiceovers</li>
              <li>Stock media suggestions for video creation</li>
              <li>Background music recommendations</li>
              <li>YouTube channel integration for video uploads</li>
              <li>Analytics and project history tracking</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">3. User Accounts</h2>
            <h3 className="text-xl font-semibold mb-3">3.1 Account Creation</h3>
            <p className="mb-4">
              To use Tivideo, you must create an account with accurate information. You are responsible for:
            </p>
            <ul className="list-disc pl-6 mb-4">
              <li>Maintaining the confidentiality of your account credentials</li>
              <li>All activities that occur under your account</li>
              <li>Notifying us immediately of any unauthorized access</li>
            </ul>

            <h3 className="text-xl font-semibold mb-3">3.2 Account Eligibility</h3>
            <p>
              You must be at least 13 years old to use Tivideo. If you are under 18, you must have 
              permission from a parent or guardian.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">4. YouTube Integration</h2>
            <h3 className="text-xl font-semibold mb-3">4.1 Authorization</h3>
            <p className="mb-4">
              When you connect your YouTube account, you authorize Tivideo to:
            </p>
            <ul className="list-disc pl-6 mb-4">
              <li>Access your YouTube channel information</li>
              <li>Upload videos to your channel (only when you initiate the upload)</li>
              <li>View analytics for videos uploaded through our service</li>
            </ul>

            <h3 className="text-xl font-semibold mb-3">4.2 YouTube Terms</h3>
            <p>
              You agree to comply with YouTube's Terms of Service and Community Guidelines. Any violation 
              may result in the termination of your Tivideo account.
            </p>

            <h3 className="text-xl font-semibold mb-3">4.3 Revocation</h3>
            <p>
              You may revoke Tivideo's access to your YouTube account at any time through your Google 
              account settings.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">5. Content and Intellectual Property</h2>
            <h3 className="text-xl font-semibold mb-3">5.1 Your Content</h3>
            <p className="mb-4">
              You retain ownership of all content you create using Tivideo, including:
            </p>
            <ul className="list-disc pl-6 mb-4">
              <li>Video scripts</li>
              <li>Generated voiceovers</li>
              <li>Project configurations</li>
            </ul>
            <p>
              By using our service, you grant us a limited license to process and store your content 
              to provide our services.
            </p>

            <h3 className="text-xl font-semibold mb-3">5.2 AI-Generated Content</h3>
            <p>
              Content generated by our AI tools is provided "as-is". You are responsible for reviewing 
              and editing AI-generated content before publication. We make no guarantees about the 
              accuracy, quality, or originality of AI-generated content.
            </p>

            <h3 className="text-xl font-semibold mb-3">5.3 Third-Party Media</h3>
            <p>
              Stock images, videos, and music suggested by Tivideo are subject to their respective 
              licenses. You are responsible for ensuring you have the right to use any third-party 
              content in your videos.
            </p>

            <h3 className="text-xl font-semibold mb-3">5.4 Our Intellectual Property</h3>
            <p>
              Tivideo's platform, software, and branding are our property. You may not copy, modify, 
              or distribute our software without permission.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">6. Acceptable Use</h2>
            <p className="mb-4">You agree not to:</p>
            <ul className="list-disc pl-6 mb-4">
              <li>Use Tivideo for any illegal or unauthorized purpose</li>
              <li>Generate content that violates copyright, trademark, or other intellectual property rights</li>
              <li>Create content that is harmful, offensive, or violates community standards</li>
              <li>Attempt to reverse engineer, hack, or compromise our service</li>
              <li>Use automated tools to access our service without permission</li>
              <li>Share your account credentials with others</li>
              <li>Resell or redistribute our service</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">7. Service Availability</h2>
            <p>
              We strive to provide reliable service, but we do not guarantee uninterrupted access. 
              We may modify, suspend, or discontinue any part of our service at any time with or 
              without notice.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">8. Pricing and Payment</h2>
            <p className="mb-4">
              Some features of Tivideo may require payment. By purchasing a subscription or service:
            </p>
            <ul className="list-disc pl-6 mb-4">
              <li>You agree to pay all applicable fees</li>
              <li>Fees are non-refundable unless required by law</li>
              <li>We may change pricing with advance notice</li>
              <li>Subscriptions auto-renew unless cancelled</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">9. Termination</h2>
            <h3 className="text-xl font-semibold mb-3">9.1 By You</h3>
            <p>
              You may terminate your account at any time through your account settings.
            </p>

            <h3 className="text-xl font-semibold mb-3">9.2 By Us</h3>
            <p>
              We may suspend or terminate your account if you violate these terms or engage in 
              fraudulent or harmful activities.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">10. Disclaimers</h2>
            <p className="mb-4">
              Tivideo is provided "as-is" without warranties of any kind. We do not guarantee:
            </p>
            <ul className="list-disc pl-6 mb-4">
              <li>The accuracy or quality of AI-generated content</li>
              <li>Uninterrupted or error-free service</li>
              <li>That our service will meet your specific requirements</li>
              <li>The security of data transmission over the internet</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">11. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Tivideo shall not be liable for any indirect, 
              incidental, special, consequential, or punitive damages arising from your use of our service.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">12. Indemnification</h2>
            <p>
              You agree to indemnify and hold Tivideo harmless from any claims, damages, or expenses 
              arising from your use of our service or violation of these terms.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">13. Changes to Terms</h2>
            <p>
              We may update these Terms of Service at any time. Continued use of Tivideo after changes 
              constitutes acceptance of the new terms.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">14. Governing Law</h2>
            <p>
              These terms are governed by the laws of the jurisdiction in which Tivideo operates, 
              without regard to conflict of law principles.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">15. Contact Information</h2>
            <p className="mb-4">
              If you have questions about these Terms of Service, please contact us at:
            </p>
            <p>
              Email: <a href="mailto:support@tivideo.app" className="text-primary hover:underline">support@tivideo.app</a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
